plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.example.ahmadr4_1'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.ahmadr4_1"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    // Firebase BOM (يحدد الإصدارات تلقائيًا)
    implementation platform('com.google.firebase:firebase-bom:33.5.1')

    // Firebase Auth
    implementation 'com.google.firebase:firebase-auth'

    // Firestore (لا تكتب رقم الإصدار هنا لأن BOM يتحكم فيه)
    implementation 'com.google.firebase:firebase-firestore'

    // Material Design
    implementation 'com.google.android.material:material:1.12.0'


    implementation 'androidx.cardview:cardview:1.0.0'
}